all: vertical palindrome

vertical: vertical.cpp
	g++ -o vertical vertical.cpp -Wall -std=c++17

palindrome: palindrome.cpp
	g++ -o palindrome palindrome.cpp pfunctions.cpp

clean: 
	rm -f vertical palindrome
